# Generated by Django 5.1.1 on 2024-09-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='task1',
            new_name='title',
        ),
    ]
