# Generated by Django 5.1.1 on 2024-09-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_rename_name_todo_details_rename_task1_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='enddate',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='todo',
            name='startdate',
            field=models.DateField(max_length=200),
        ),
    ]
